### ISSUE TITLE
Stupid question about using the code

### ISSUE THREAD

**Issue by mrcocytus** [zhanghaoyu1993/RC-experiments#1]
hello,
I'm starting to use your code, but actually don't understand the [module.model_class] and the args.json in your readme, so I don't know how to test the code. Can you give the specific usage, or just give me the example to type the command. Thank you.

**Comment by cairoHy** [comment]
Module is the file name of model, model_class is the class name of model. For example, if you want to test AoA-Reader, the command is 
```bash
python attention_over_attention_reader.AoAReader ....
```

**Comment by mrcocytus** [comment]
When I ran the epoch 2, unluckily I got the following issue.

17-05-29 03:12 Samples : 70528/108719.	Step : 2203/3397.	Loss : 0.6614.	Accuracy : 0.7463
17-05-29 03:12 Validate on 63 batches, 32 samples per batch, 2000 total.
17-05-29 03:15 Evaluate on : 2000/2000.	Val acc : 0.7570.	Val Loss : 0.6754
17-05-29 03:15 Oh u, stop training.
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f5e5068f588>>
Traceback (most recent call last):
  File "/home/mrcocytus/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'

But I have installed the tensorflow 1.1.0 and other packages needed. Can you help me with this problem?

**Comment by mrcocytus** [comment]
Hello,
I wonder how to write the predicted answer of the test set into a fie.

**Comment by cairoHy** [comment]
The accuracy variable(and other information) will be stored to a file named result.json after test, you don't need to store it manually.

**Comment by cairoHy** [comment]
It's because i don't close tensorflow session after execution, but the
result will not be influenced, and your training is ending normally with
val acc of 0.7570.

**Comment by mrcocytus** [comment]
Thank you for your help. 
I mean that how to store the predicted answers to the cloze-style reading comprehension, the result.json only contains accuracy, not answers to the test set.

**Comment by cairoHy** [comment]
You have to write the code by yourself, i didn't implement the function.

**Comment by mrcocytus** [comment]
Can you kindly give me some ideas about that?

**Comment by cairoHy** [comment]
You should modify the model you use(for example models/attention_sum_reader.py), and let it return the predictions).
Next modify the test method of models/rc_base.py, and calculate the predictions and serialize it.
