### ISSUE TITLE
from .r_net import RNet

### ISSUE THREAD

**Issue by johndpope** [zhanghaoyu1993/RC-experiments#2]
can find this python package.
any ideas?

    from .r_net import RNet
ImportError: cannot import name 'RNet'

**Comment by cairoHy** [comment]
RNet is not implemented completely yet, so the file is not committed.


[r_net.zip](https://github.com/cairoHy/RC-experiments/files/1209924/r_net.zip)
To run the code, unzip this zip file, and put the r_net.py into models/ folder, the error should be fixed.

**Comment by johndpope** [comment]
thanks - throwing up this gist for others.
https://gist.github.com/johndpope/4c820e798554349df883f0037cfd9905
