### ISSUE TITLE
Why manual computation of crossentropy?

### ISSUE THREAD

**Issue by suriyadeepan** [zhanghaoyu1993/RC-experiments#3]
https://github.com/cairoHy/RC-experiments/blob/0262f83481c364f29a43ac7cfc28da88d31f5adc/models/attention_sum_reader.py#L115-L120

**Comment by cairoHy** [comment]
Personal choice, you can change to the cross entropy function.

**Comment by cairoHy** [comment]
Personal choice, cross entropy function provided in tensorflow works too.

**Comment by suriyadeepan** [comment]
thanks for the quick reply!
