### ISSUE TITLE
Trying to work it with SQuAD

### ISSUE THREAD

**Issue by uditadhikari** [zhanghaoyu1993/RC-experiments#5]
Having difficulty using this for the dataset from here:
https://rajpurkar.github.io/SQuAD-explorer/

Any suggestions on how to modify this code base.

**Comment by cairoHy** [comment]
Refer to [this repo](https://github.com/HKUST-KnowComp/R-Net), it is the [r-net]( https://www.microsoft.com/en-us/research/wp-content/uploads/2017/05/r-net.pdf) implementation on SQuAD.
